# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
    MY_IMAGE_NAME: caddy-cloudflare

jobs:
  push_github:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v4
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v4
        if: ${{ steps.caddy_version.outputs.caddy_version }} != ${{ steps.my_version.outputs.my_version }}
        with:
          context: .
          push: $ {{ github.event.pull_request.merged == true || github.event.name == 'PushEvent' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.MY_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.MY_IMAGE_NAME }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm/v7
