# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '20 20 * * *'  # 8:20pm everyday
  push:
    branches:
      - main
env:
    IMAGE_NAME: caddy-cloudflare

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      upstream_version: ${{ steps.check_upstream.outputs.upstream }}
      my_version: ${{ steps.check_my.outputs.my }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: check_upstream
        run: |
          docker pull docker.io/library/caddy
          version=$(docker image inspect --format '{{json .}}' caddy | jq .RepoTags | grep -E ':[0-9]' | tr -d " \",")
          echo "upstream=$version" >> "$GITHUB_OUTPUT"
      - id: check_my
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          version=$(docker image inspect --format '{{json .}}' ${{ env.IMAGE_NAME }} | jq .RepoTags | grep -E ':[0-9]' | tr -d " \",")
          echo "my=$version" >> "$GITHUB_OUTPUT"

  push_github:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: check_version
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          UPSTREAM_VERSION: ${{needs.check_version.outputs.upstream_version}}
          MY_VERSION: ${{needs.check_version.outputs.my_version}}
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest,ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.UPSTREAM_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm/v7
          buildArgs: basetag=${{ env.UPSTREAM_VERSION }},buildertag=${{ env.UPSTREAM_VERSION }}-builder
