# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '20 20 * * *'  # 8:20pm everyday
  push:
    branches:
      - main
env:
    MY_IMAGE_NAME: caddy-cloudflare

jobs:
  push_github:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check caddy metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: docker.io/library/caddy:latest
          tags: type=semver,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          UPSTREAM_VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.MY_IMAGE_NAME }}:latest,ghcr.io/${{ github.repository_owner }}/${{ env.MY_IMAGE_NAME }}:${{ env.UPSTREAM_VERSION }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.MY_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.MY_IMAGE_NAME }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm/v7
          build-args: |
            basetag=${{ env.UPSTREAM_VERSION }}
            buildertag=${{ env.UPSTREAM_VERSION }}-builder
